name: CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Gateway Image
        run: |
          cd server/api-gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mydrive-api-gateway:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mydrive-api-gateway:latest

      - name: Build and Push Metadata Service Image
        run: |
          cd server/metadata-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mydrive-metadata-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mydrive-metadata-service:latest

      - name: Build and Push Upload Service Image
        run: |
          cd server/upload-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mydrive-upload-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mydrive-upload-service:latest

      - name: Deploy with Docker Compose
        run: |
          cd server
          docker-compose down
          docker-compose pull
          docker-compose up -d
